[package]
name = "hello_world"
version = "0.1.0"
authors = ["Utkarsh Mani Tripathi <utkarshmani1997@gmail.com>"]
edition = "2018"

[dependencies]
libzfs = { git = "https://github.com/gila/rust-libzfs", branch = "0712" }
